---
kind: pipeline
type: docker
name: leetcode

steps:
  - name: go test
    image: golang
    commands:
      - go test
    extra_hosts:
      - "drone.minbaby.cc:192.168.5.184"
      - "gitea.minbaby.cc:192.168.5.184"
trigger:
  branch:
    - master
  event:
    - push