---
kind: pipeline
type: docker
name: leetcode

steps:
  - name: go test
    image: golang:1.14.2-alpine3.11
    pull: if-not-exists
    commands:
      - cd go && CI_ENV=1 go test -failfast -timeout=3s ./...

  - name: send-wechat
    image: erguotou/drone-instant-access
    pull: if-not-exists
    settings:
      channel:
        from_secret: CHANNEL
      head: "[${DRONE_REPO}] Build Status"
      body: "[${DRONE_REPO}] ${DRONE_STAGE_STATUS} at ${DRONE_COMMIT_BRANCH} branch"
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master