#!/usr/bin/env php
<?php

if ($argc != 3) {
    echo <<<EOF
{$argv[0]} {nums} {url}

EOF;
exit(-1);
}

$url = parse_url($argv[2], PHP_URL_PATH);
$arr = array_values(array_filter(explode('/', $url)));
$t = $arr[1];

$dir = "src/main/{$argv[1]}-{$arr[1]}";
echo "检查目录 ", __DIR__ . '/' . $dir,  PHP_EOL;
@mkdir(__DIR__ . '/' . $dir);

$target = [
    "{$argv[1]}.h",
    "{$argv[1]}.c",
    "{$argv[1]}_test.c",
];

foreach (glob(__DIR__ . '/stubs/*') as $value) {
    $content = file_get_contents($value);
    $content = str_replace('{num}', $argv[1], $content);
    $content = str_replace('{url}', $argv[2], $content);
    $name = pathinfo($value, PATHINFO_BASENAME);
    $name = str_replace('{num}', $argv[1], $name);
    
    $file = __DIR__ . "/$dir/$name";
    echo "生成文件 $file", PHP_EOL;

    file_put_contents($file, $content);
}
