env:
  BUILD_TYPE: Release

on: push

jobs:
  #  example:
  #    runs-on: ubuntu-20.04
  #    steps:
  #      - name: Setup cmake
  #        uses: jwlawson/actions-setup-cmake@v1.9
  #        with:
  #          cmake-version: '3.16.x'
  #      - name: Use cmake
  #        run: cmake --version
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.16.x'
      - name: Install Criterion
        run: cd /tmp && wget -qO- https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 | tar -xjvf - && sudo cp -a criterion-v2.3.3/lib/. /usr/lib && sudo cp -a criterion-v2.3.3/include/. /usr/include && sudo cp -a criterion-v2.3.3/share/pkgconfig/. /usr/share/pkgconfig
      - name: Configure Cmake
        working-directory: ${{github.workspace}}/c
        run: cmake -B ${{github.workspace}}/c/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        working-directory: ${{github.workspace}}/c
        run: cmake --build ${{github.workspace}}/c/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/c/build
        run: ./runtest
